[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_tax_token_anchor = "2uTRyNTYcwZSWkm9hqxS6gXKdNz67avDRKZzqDesJdeb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/riteshnikhoria31/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
